#ifndef LIB_UNSORTEDTABLEONARR_UNSORTEDTABLEONARR_H_
#define LIB_UNSORTEDTABLEONARR_UNSORTEDTABLEONARR_H_

template <class TKey, class TValue>
class UnsortedTableM : public ITable<TKey, TValue> {

};

#endif //LIB_UNSORTEDTABLEONARR_UNSORTEDTABLEONARR_H_